llama3-8b:
  hf_key: "meta-llama/Meta-Llama-3-8B"
  question_start_tag: "<|start_header_id|>user<|end_header_id|>\n\n"
  question_end_tag: "<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"

qwen2.5-7b:
  hf_key: "Qwen/Qwen2.5-7B"
  question_start_tag: "<|im_start|>user\n"
  question_end_tag: "<|im_end|>\n<|im_start|>assistant\n"
  answer_tag: ""
  flash_attention2: "true"
  gradient_checkpointing: "true"
